export const errorCodes = [
  "VALIDATION_ERROR",
  "EMAIL_ALREADY_EXISTS",
  "INVALID_CREDENTIALS",
  "CURRENT_PASSWORD_INCORRECT",
  "AUTH_REQUIRED",
  "INVALID_TOKEN",
  "TOKEN_REVOKED",
  "FORBIDDEN",
  "TOO_MANY_REQUESTS",
  "ROUTE_NOT_FOUND",
  "DATABASE_UNAVAILABLE",
  "MALFORMED_JSON",
  "PAYLOAD_TOO_LARGE",
  "INTERNAL_SERVER_ERROR",
] as const;

export type ErrorCode = (typeof errorCodes)[number];
